Fix for 360° lidars.
SteveMacenski/slam_toolbox pull request #145
Opened 2020-01-08 14:54 UTC by SelvamArul

I followed option 2 as you mention in #141 comments.
Please take a look at the changes, and lemme know if it looks good.

2020-01-11 05:37 UTC, SteveMacenski requested changes

2020-01-11 05:37 UTC, SteveMacenski commented on src/laser_utils.cpp
> +  if ( (std::fabs(scan_.angle_min + M_PI) < 1e-3) &&
huh, not the way I would have done this but probably cleaner. Nice.

2020-01-11 05:37 UTC, SteveMacenski commented on src/laser_utils.cpp
> +  laser->SetIs360Laser(is_360_lidar);
You're setting a bool, but getting a double, that doesn't make much sense.

2020-01-11 05:37 UTC, SteveMacenski commented on lib/karto_sdk/include/karto_sdk/Karto.h
> +      int laserResidual = !GetIs360Laser();
You find if its 360 and give it a bool, the variable is implicitly stored as a bool, the `Get` is a double, and you're assigning it an int. This needs to be cleaned up.

2020-01-11 05:39 UTC, SteveMacenski commented
Better option than the 2 I provided, but need to make sure the types are consistent and valid. If you store the "is360lidar" that is implicitly a boolean. You should assign the int for how many to add based on the boolean value. 

Basically: the `get` and `set` should be `bool`s, and you can use the `Get` to assign the `residual` as `0` or `1`.

2020-01-16 10:26 UTC, SelvamArul commented
Ja, the return type of  `GetIs360Laser` should have been `kt_bool`. It was copy-paste error. I fixed it. Getting `is360lidar` as bool and assigning `laserResidual` (of type int) based on `is360lidar` is done as you suggested :)

2020-01-16 19:39 UTC, SteveMacenski commented
@SelvamArul thanks for fixing the `kt_double`!

Still a (bug? not really a bug... confusing abstraction?) thing with the `int residual = !GetIs360Lidar()`.

I see logically that is sound, but its really not straight forward that you're converting the inverse of a boolean as an integer. It makes it hard to read and understand at first glance. Can you change to something like:

```
int residual = 1;
if (GetIs360Lidar()) 
{
  residual = 0;
}

```

2020-01-17 10:24 UTC, SelvamArul commented
I agree with bool to int conversion readability. Changed the code to make it more explicit as you suggested.

2020-01-17 19:24 UTC, SteveMacenski approved these changes
LGTM

Letting it sit for a hot minute while I cherry pick over to Eloquent and Dashing. If its not still merged next time you see it and you're willing, I'd appreciate it. There's alot on my plate this week.

2020-01-17 22:26 UTC, merged

2020-01-17 22:26 UTC, SteveMacenski commented
Thanks for your contribution!