fix issue (#333) initial scan not added to localization buffer [foxy]
SteveMacenski/slam_toolbox pull request #343
Opened 2021-03-02 16:51 UTC by PGotzmann

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #333 |
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | Gazebo simulation |

---

## Description of contribution in a few bullet points
- added parameter to `Mapper::ProcessAgainstNodesNearBy()` to selectively add scan to localization buffer if in localization mode, otherwise (SLAM mode) do as before.
- extracted method for adding new scan to localization buffer
- fixed off-by-one error of localization buffer size

## Description of documentation updates required from your changes

No documentation updates required

---

## Future work that may be required in bullet points

This patch is also required for previous ROS2 version.

2021-03-02 19:28 UTC, SteveMacenski requested changes
Mostly just linting, but LGTM otherwise if you tested it. Please update in ROS2/Melodic/Noetic after the linting updates :+1:

2021-03-02 19:28 UTC, SteveMacenski commented on lib/karto_sdk/include/karto_sdk/Mapper.h
> +  kt_bool ProcessAgainstNodesNearBy(LocalizedRangeScan * pScan, kt_bool localizationMode = false);
```suggestion
  kt_bool ProcessAgainstNodesNearBy(LocalizedRangeScan * pScan, kt_bool addScanToLocalizationBuffer = false);
```

2021-03-02 19:28 UTC, SteveMacenski commented on lib/karto_sdk/src/Mapper.cpp
> +kt_bool Mapper::ProcessAgainstNodesNearBy(LocalizedRangeScan * pScan, kt_bool localizationMode)
```suggestion
kt_bool Mapper::ProcessAgainstNodesNearBy(LocalizedRangeScan * pScan, kt_bool addScanToLocalizationBuffer)
```

2021-03-02 19:28 UTC, SteveMacenski commented on lib/karto_sdk/src/Mapper.cpp
> +    if (localizationMode){
```suggestion
    if (addScanToLocalizationBuffer) {
```

2021-03-02 19:28 UTC, SteveMacenski commented on lib/karto_sdk/src/Mapper.cpp
> +void Mapper::AddScanToLocalizationBuffer(LocalizedRangeScan *pScan, Vertex <LocalizedRangeScan> *scan_vertex)
```suggestion
void Mapper::AddScanToLocalizationBuffer(LocalizedRangeScan * pScan, Vertex <LocalizedRangeScan> * scan_vertex)
```

2021-03-06 02:01 UTC, SteveMacenski approved these changes
Assuming you've tested this to work, I'm happy with it. Please submit against `ros2` `noetic` and `melodic` and `dashing` at the minimum as well so all of them can get this patch

2021-03-08 14:18 UTC, PGotzmann commented
Sorry for keeping you waiting.
I have in the meantime tested it and the fix itself seems to work as desired.

However, I have thereby encountered another problem, which I believe to be independent of this change after some more testing.

I have tried to create an issue (#355) based on the information I have so far but I am still struggling to really get a grip on the real problem here.
Maybe that tells you something anyway.

2021-03-08 20:20 UTC, SteveMacenski approved these changes

2021-03-09 13:05 UTC, PGotzmann commented
> Assuming you've tested this to work, I'm happy with it. Please submit against `ros2` `noetic` and `melodic` and `dashing` at the minimum as well so all of them can get this patch

done :wink: 
Please note, that again I have only been able to really test this on `foxy`.

2021-03-09 19:36 UTC, merged