fixed timestamps input&output not synchronized
SteveMacenski/slam_toolbox pull request #377
Opened 2021-04-08 10:02 UTC by ohsirawat

## Basic Info

| Info | Please fill out this column |
| ------ |------|
| Ticket | #376 
| Test on | Ubuntu 20.04 ROS2 Foxy, rosbag 

---

## Description of contribution in a few bullet points

*  I changed msg.header.stamp in `SlamToolbox::updateMap` and `SlamToolbox::publishTransformLoop` from this->now() to latest `/scan` timestamps (store in ::laserCallback)  
 
## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

2021-04-12 18:05 UTC, SteveMacenski reviewed
A couple of small changes and LGTM

2021-04-12 18:05 UTC, SteveMacenski commented on include/slam_toolbox/visualization_utils.hpp
> +  marker.lifetime = rclcpp::Duration(0.);
Return back to `from_nanoseconds`

2021-04-12 18:05 UTC, SteveMacenski commented on src/slam_toolbox_common.cpp
> +      msg.header.stamp = scan_timestamped + transform_timeout_; // 8 Apr.21 | remove this->now
No need for the comment, git history will have this.

2021-04-14 08:34 UTC, ohsirawat commented
Thanks!, resolved

2021-04-14 18:06 UTC, SteveMacenski requested changes
LGTM, but please run the linters, I'm seeing several violations

2021-04-16 10:40 UTC, ohsirawat commented
You mean ament_cpplint right? I removed those extra spaces. Thanks for pointing out.

2021-04-16 18:14 UTC, SteveMacenski approved these changes

2021-04-16 18:14 UTC, merged

2021-04-16 18:14 UTC, SteveMacenski commented
Thanks!