Add service to toggle in and out of localization mode.
SteveMacenski/slam_toolbox pull request #512
Opened 2022-07-11 19:34 UTC by malban

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  |
| Primary OS tested on | Ubuntu 18.04 |
| Robotic platform tested on | gazebo simulation of small indoor robot with single plane lidar |

---

## Description of contribution in a few bullet points

See #510

* Added service to base class to enable switching between localization and mapping modes

Example use case would be to explore an area while building up a map in map mode and then switch to localization mode to perform tasks within that area. 

## Description of documentation updates required from your changes

* Added new service to the README documentation.

---

## Future work that may be required in bullet points

2022-07-12 01:22 UTC, malban commented
Rebased and updated to publish covariance from #511

2022-07-18 18:01 UTC, SteveMacenski requested changes
Otherwise, LGTM

2022-07-18 18:01 UTC, SteveMacenski commented on include/slam_toolbox/experimental/slam_toolbox_map_and_localization.hpp
> + * Copyright 2022 Hatchbed L.L.C.
This is highly derivative of existing work, the copyright header should be the same as the other nodes.

2022-07-18 18:01 UTC, SteveMacenski commented on src/experimental/slam_toolbox_map_and_localization_node.cpp
> + * Redistribution and use in source and binary forms, with or without
As well

2022-07-18 19:29 UTC, malban commented on src/experimental/slam_toolbox_map_and_localization_node.cpp
> + * Redistribution and use in source and binary forms, with or without
Fixed the licenses.

2022-07-19 19:12 UTC, SteveMacenski approved these changes

2022-07-19 19:12 UTC, merged