Add Reset Map
SteveMacenski/slam_toolbox pull request #673
Opened 2024-02-21 14:29 UTC by lekoook

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #640  |
| Primary OS tested on | Ubuntu 22.04 |
| Robotic platform tested on | (Turtlebot 4 Gazebo Sim) |

---

## Description of contribution in a few bullet points

* Added a new `slam_toolbox::Reset` Service.
* Upon calling of said service, the current map will be "cleaned" and reset back to the initial state.
* A new clean map can then be generated from there.
* `slam_toolbox::Reset` request also contains a boolean `pause_new_measurements` that if set to `true`, subsequent new scans will be ignored until a `slam_toolbox::Pause` is called to resume.
* Tested with nodes: `async_slam_toolbox_node`, `sync_slam_toolbox_node`, `localization_slam_toolbox_node`

## Description of documentation updates required from your changes

* Added a new service with the default Service name: `/slam_toolbox/reset` and message type: `slam_toolbox::Reset`
* Proposed API description: `Reset current map back to the initial state`

---

## Future work that may be required in bullet points

* Considerations for experimental nodes: `map_and_localization_slam_toolbox_node`, `lifelong_slam_toolbox_node`

2024-02-21 17:14 UTC, SteveMacenski requested changes
Generally looks good to me, a couple of details here and this is ready to go. You also need to document this in the table of exposed services in the readme.

2024-02-21 17:14 UTC, SteveMacenski commented on srvs/Reset.srv
> +bool pause_new_measurements
Set to false by default

2024-02-21 17:14 UTC, SteveMacenski commented on src/slam_toolbox_common.cpp
> +  {
Linting issues

2024-02-21 17:14 UTC, SteveMacenski commented on src/slam_toolbox_common.cpp
> +  {
Run ament_uncrustify / ament_cpplint

2024-02-21 18:57 UTC, lekoook commented on srvs/Reset.srv
> +bool pause_new_measurements
Sorry, I might be misunderstanding something, do you mean to set the pause state for NEW_MEASUREMENTS to false in the service callback?

2024-02-21 19:08 UTC, SteveMacenski commented on srvs/Reset.srv
> +bool pause_new_measurements
Oh, no, if you change it to:

```
bool pause_new_measurements False
```

Then unless a user specifically sets `pause_new_measurements` in the action to `True`, it'll default to false. That way the reset, by default, doesn't stop processing new scans, just resets the current state.

2024-02-22 03:37 UTC, lekoook commented on srvs/Reset.srv
> +bool pause_new_measurements
Got it, made the necessary changes.

2024-02-22 03:38 UTC, lekoook commented on src/slam_toolbox_common.cpp
> +  {
Fixed linting issues.

2024-02-22 05:09 UTC, SteveMacenski approved these changes

2024-02-22 05:09 UTC, merged

2024-02-22 05:09 UTC, SteveMacenski commented
Nice contribution, thanks!